### PR TITLE
Julia 0.7

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Fails on Julia 0.7 with the message
```
$ julia -E 'using BinDeps; BinDeps.debug("MUMPS")'
ERROR: ArgumentError: Package BinDeps not found in current path:
- Run `Pkg.add("BinDeps")` to install the BinDeps package.
```
But BinDeps appears in REQUIRE?!?!

**Comment by abelsiqueira** [comment]
Not sure what's wrong with BinDeps. [BinaryBuilder](https://github.com/JuliaPackaging/BinaryBuilder.jl) seems to be a better alternative, though very different to use. [Video from JuliaCON2018](https://www.youtube.com/watch?v=2e0PBGSaQaI).

On the MPI version, do you want to limit to 0.6.0 and not 0.7.0? I think it's
`MPI 0.6.0 0.7.0`

**Comment by dpo** [comment]
I just can't get MPI.jl to build properly on Linux. Using Ubuntu packages results in errors, and so does building OpenMPI from source.

**Comment by dpo** [comment]
Not working on OSX anymore either...

**Comment by abelsiqueira** [comment]
MPI.jl has a [travis-installer](https://github.com/JuliaParallel/MPI.jl/tree/v0.6.0/conf), maybe we can use that?

**Comment by dpo** [comment]
Closing this as outdated.

**Pull request closed without merging**
