### PR TITLE
[Documentation] hotfix

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by dpo** [comment]
Why are you merging? There are tons of errors in the docs build. That's why I turned `strict` to `true`...

**Comment by amontoison** [comment]
Because I fixed the issue with Homebrew.
The other errors are related to the docs build and not Homebrew.

**Comment by dpo** [comment]
I understand (and thank you) but now we lost #83 and the failed docs build :-(

**Comment by amontoison** [comment]
I started to fix it with a new branch, I wasn't just able to finish it today.
It's a good idea to keep #85 as a reminder.

**Pull request merged**
