### PR TITLE
Initial move to MUMPS native C-API

### PR DESCRIPTION
**Pull request by wrs28**
Per [Issue #46](https://github.com/JuliaSmoothOptimizers/MUMPS.jl/issues/46), here is a first pass at upgrading `MUMPS.jl` to using the MUMS C-API.
See commit comments for details, but essentially this PR keeps both the original code and ports `MUMPS3.jl`. For now there are two `include` lines in `MUMPS.jl` which govern which set of codes is used. It is easy for a developer to toggle between the two for testing.

The exported methods of this PR have the same signature as the original codes, and no new methods are exported. All tests pass with both codes, with one test being slightly modified as noted in the [commit comment](https://github.com/JuliaSmoothOptimizers/MUMPS.jl/commit/d010ca4c077cd5fcc2e3e86d3ea091ee0535eb5b), as does the example in `examples/mumps_mpi.jl`, again, with suitable updating. This is so that anyone using `MUMPS.jl` will experience minimal changes.

As it stands, sparse rhs is now supported. Other features, such as computing and accessing the Schur complement are implemented inside the code, but not exported.

### CODE REVIEW

**Comment by dpo** [comment]
Many, many thanks for this. I need a little time to review and test but will do asap!

**Comment by wrs28** [comment]
Do take your time. I'm sure there is something that will break that I missed, and it's important to get it right.

**Comment by wrs28** [comment]
@dpo have you had a chance to look at this? There’s probably some updating to do to make compatible with Julia 1, but it can probably wait till the initial port is done

**Comment by dpo** [comment]
@wrs28 Sorry for the long delay. I've been overloaded. I really do want to merge this but it'll have to wait until January.

**Comment by dpo** [comment]
Merged in #64.

**Pull request closed without merging**
