### PR TITLE
Test local install

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
It's hard to know if the external library is being used or not. The info message doesn't show. I tried `using MUMPS` before `using Test`, but that didn't show anything either.

**Comment by dpo** [comment]
don't force-push until finalized; otherwise we can't see what you changed.

**Comment by amontoison** [comment]
> don't force-push until finalized; otherwise we can't see what you changed.

I just rebased. I don't force-push otherwise.

**Comment by amontoison** [comment]
> It's hard to know if the external library is being used or not. The info message doesn't show. I tried `using MUMPS` before `using Test`, but that didn't show anything either.

The external library is not used: https://github.com/JuliaSmoothOptimizers/MUMPS.jl/runs/8006282188?check_suite_focus=true#step:6:103.

**Review by amontoison — APPROVED** [review]

**Comment by amontoison** [comment]
I was looking a `CI_M1` build instead of a CI-Homebrew` build....
The custom installation works fine.
I added a constant `MUMPS_INSTALLATION` to easily see if we have custom installation or not in the tests.

**Comment by dpo** [comment]
Excellent, thank you!

**Pull request merged**
