### PR TITLE
Test MUMPS_seq_jll 5.5.1 with MKL

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
We also have the null pointer on Windows if we use `MKL_jll` instead of `OpenBLAS32_jll`.
The tests also fail on Mac if we use `MKL_jll`.

**Comment by dpo** [comment]
This failure points to a BLAS mixup. It's the same failure we were having before you fixed the JLL.

**Comment by amontoison** [comment]
> This failure points to a BLAS mixup. It's the same failure we were having before you fixed the JLL.

MKL only works if it's single threaded on Mac...
https://github.com/JuliaLinearAlgebra/MKL.jl/issues/111

It should be more relevant to use [`Apple Accelerate`](https://github.com/chriselrod/AppleAccelerateLinAlgWrapper.jl) on Apple platforms.
```
LinearAlgebra.BLAS.lbt_forward("/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate")
```
I just don't know if it's a LP64 or ILP64 BLAS.

**Comment by dpo** [comment]
I don'think it uses 64 bit Ints.

**Comment by amontoison** [comment]
The issue was fixed in LBT 5.4.0, which is available with Julia >= 1.9.

**Pull request closed without merging**
